### ISSUE TITLE
hdr download failed

### ISSUE THREAD

**Issue by chrober24** [ktkk/hdrihaven-downloader#3]
Hi I just tried running this in anaconda but none of the files downloaded. 

`Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Anaconda3\envs\hdri\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "C:\Anaconda3\envs\hdri\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range`

Any ideas how to fix this?

**Comment by ktkk** [comment]
I am not familiar with Anaconda. It looks like this is an issue with their version of fake-useragent, rather than with this script. I just tested it with the pip3 version of fake-useragent and it worked fine.

**Comment by chrober24** [comment]
Thanks for your reply. Could you tell me what version of fake-useragent you used? I installed with pip and it downloaded 0.1.11

**Comment by chrober24** [comment]
I checked with different versions of fake-useragent and still can't download anything. This time I got an http 404 error. I just checked out the structure of the website. I'm still pretty new to coding so I may be getting things wrong, but the href for the download link goes to https://polygonhaven.com now because they're currently switching to a new website. Could this have anything to do with it? Though you just said it still works for you

**Comment by ktkk** [comment]
Just checked fake-useragent and I'm also in 0.1.11.
I ran the script again and I've noticed it does indeed throw the same error you were getting, though after that it just continues downloading the hdri's. Maybe you're quitting too early?
I don't think the link is wrong. https://hdrihaven.com still exists for me and does not redirect me to anything.

**Comment by chrober24** [comment]
I just let the script run all the way to the end and still didn't get any images. There were no errors this time, but it still says download failed for every image. I can't think of any reason it wouldn't work for me if it does for you.

**Comment by ktkk** [comment]
I updated the URL since it seems like they've fully switched to the new website. Could you perhaps try if this fixes your issue?

EDIT: nvm, seems like the new website completely ruined it. Working on a fix.

**Comment by ktkk** [comment]
I've rewritten the script to make use of the new Polyhaven API. I think this should resolve any issue you were having. If it didn't, please feel free to open a new issue.
